import { NextResponse } from "next/server";
import { adminApiError, recordIdentifier } from "@/lib/admin-api";
import { readJsonObject } from "@/lib/http";
import { requireStaffPermission } from "@/lib/staff-auth";
import { createSupabaseServerClient } from "@/lib/supabase/server";

const tables = { enquiries:"enquiries", leads:"lead_submissions", journeys:"study_journey_enquiries", subscriptions:"deadline_subscriptions" } as const;
export async function PATCH(request:Request,{params}:{params:Promise<{type:string}>}){try{await requireStaffPermission("leads.manage");const {type}=await params;const table=tables[type as keyof typeof tables];if(!table)throw new Error("Unsupported lead type.");const input=await readJsonObject(request);const allowed=table==="deadline_subscriptions"?["active","unsubscribed"]:["new","in_progress","closed"];if(!allowed.includes(String(input.status)))throw new Error("Invalid lead status.");const supabase=await createSupabaseServerClient();const {data,error}=await supabase.from(table).update({status:input.status}).eq("id",recordIdentifier(input.id)).select("id").maybeSingle();if(error)throw new Error("Unable to update the lead.");if(!data)throw new Error("Lead not found.");return NextResponse.json({ok:true});}catch(error){return adminApiError(error);}}
export async function POST(request:Request,{params}:{params:Promise<{type:string}>}){try{const context=await requireStaffPermission("leads.manage");const {type}=await params;const table=tables[type as keyof typeof tables];if(!table)throw new Error("Unsupported lead type.");const input=await readJsonObject(request);if(typeof input.body!=="string"||!input.body.trim()||input.body.length>4000)throw new Error("Enter a valid triage note.");const supabase=await createSupabaseServerClient();const {error}=await supabase.from("lead_triage_notes").insert({lead_table:table,lead_id:recordIdentifier(input.id),body:input.body.trim(),created_by:context.user.id});if(error)throw new Error("Unable to add the triage note.");return NextResponse.json({ok:true});}catch(error){return adminApiError(error);}}
