"use client";
import { useState } from "react";

type Revision={id:string;created_at:string;revision_note:string|null;content:Record<string,string>;seo_title:string|null;seo_description:string|null;open_graph:Record<string,unknown>};
export function AdminCmsEditor({slug,defaults,page,revisions,canManage,canPublish}:{slug:string;defaults:Record<string,string>;page:{id:string;status:string;seo_title:string|null;seo_description:string|null;published_revision_id:string|null}|null;revisions:Revision[];canManage:boolean;canPublish:boolean}){
  const latest=revisions[0];const [content,setContent]=useState({...defaults,...(latest?.content??defaults)});const [seoTitle,setSeoTitle]=useState(latest?.seo_title??page?.seo_title??"");const [seoDescription,setSeoDescription]=useState(latest?.seo_description??page?.seo_description??"");const [message,setMessage]=useState("");
  async function submit(values:Record<string,unknown>){setMessage("Saving…");const response=await fetch("/api/admin/cms",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,...values})});const result=await response.json();if(!response.ok)return setMessage(result.message??"Unable to save.");window.location.reload();}
  return <div className="ops-cms-editor"><section className="ops-card"><div className="ops-status-line"><span className={`ops-badge is-${page?.status??"draft"}`}>{page?.status??"draft"}</span><span>{revisions.length} revision{revisions.length===1?"":"s"}</span></div><div className="ops-form-grid">{Object.entries(defaults).map(([key])=><label key={key} className="is-wide"><span>{key.replaceAll(/([A-Z])/g," $1").replaceAll("_"," ")}</span><textarea rows={key.toLowerCase().includes("description")?4:2} value={content[key]??""} disabled={!canManage} onChange={(event)=>setContent((current)=>({...current,[key]:event.target.value}))}/></label>)}{canManage&&<><label><span>SEO title</span><input value={seoTitle} maxLength={255} onChange={(event)=>setSeoTitle(event.target.value)}/></label><label><span>SEO description</span><textarea value={seoDescription} maxLength={500} onChange={(event)=>setSeoDescription(event.target.value)}/></label><label className="is-wide"><span>Revision note</span><input id="cms-revision-note" maxLength={500}/></label></>}</div>{canManage&&<button className="ops-primary" onClick={()=>void submit({action:"save",content,seo_title:seoTitle,seo_description:seoDescription,revision_note:(document.getElementById("cms-revision-note") as HTMLInputElement).value})}>Save draft revision</button>}<p role="status">{message}</p></section><aside className="ops-card"><h2>Draft and publication history</h2>{revisions.map((revision)=><article className="ops-revision" key={revision.id}><strong>{new Date(revision.created_at).toLocaleString("en-GB")}</strong><span>{revision.revision_note||"No note"}</span><div><a href={`/api/admin/cms/preview?slug=${encodeURIComponent(slug)}&revision=${revision.id}`} target="_blank" rel="noreferrer">Preview actual page ↗</a>{canPublish&&<button onClick={()=>void submit({action:page?.published_revision_id===revision.id?"unpublish":"publish",revision_id:revision.id})}>{page?.published_revision_id===revision.id?"Unpublish":"Approve and publish"}</button>}</div></article>)}{!revisions.length&&<div className="ops-empty">Save a draft to preview the actual page.</div>}</aside></div>;
}
