"use client";
import { useRef,useState } from "react";
import type { AdminEntity } from "@/lib/admin-registry";

type Row=Record<string,unknown>;
const shown=(value:unknown)=>typeof value==="boolean"?(value?"Published / active":"Draft / inactive"):value==null||value===""?"—":typeof value==="object"?JSON.stringify(value):String(value);

export function AdminCrudManager({entity,rows,canManage}:{entity:AdminEntity;rows:Row[];canManage:boolean}){
  const dialog=useRef<HTMLDialogElement>(null);const [editing,setEditing]=useState<Row|null>(null);const [message,setMessage]=useState("");
  const endpoint=`/api/admin/${entity.permissionDomain}/${entity.key}`;
  function open(row:Row|null){setEditing(row);setMessage("");dialog.current?.showModal();}
  async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setMessage("Saving…");const data=new FormData(event.currentTarget);const values:Row={};for(const field of entity.fields){values[field.key]=field.type==="boolean"?data.get(field.key)==="on":data.get(field.key)??"";}if(editing)values.id=editing[entity.idKey];const response=await fetch(endpoint,{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(values)});const result=await response.json();if(!response.ok)return setMessage(result.message??"Unable to save.");window.location.reload();}
  async function remove(row:Row){if(!window.confirm(`Delete this ${entity.label.toLowerCase()} record? This cannot be undone.`))return;const response=await fetch(endpoint,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:row[entity.idKey]})});const result=await response.json();if(!response.ok)return setMessage(result.message??"Unable to delete.");window.location.reload();}
  const columns=[entity.idKey,...entity.fields.slice(0,4).map((field)=>field.key)];
  return <section className="ops-crud"><div className="ops-toolbar"><form method="get" role="search"><label><span className="sr-only">Search {entity.label}</span><input name="q" type="search" placeholder={`Search ${entity.label.toLowerCase()}…`} /></label><select name="state" aria-label="Publication filter"><option value="">All states</option><option value="published">Published / active</option><option value="draft">Draft / inactive</option></select><button>Filter</button></form>{canManage&&<button className="ops-primary" onClick={()=>open(null)}>Add {entity.label.replace(/s$/i,"")}</button>}</div><p role="status">{message}</p><div className="ops-table-wrap"><table><thead><tr>{columns.map((column)=><th key={column}>{entity.fields.find((field)=>field.key===column)?.label??"ID"}</th>)}{canManage&&<th>Actions</th>}</tr></thead><tbody>{rows.map((row)=><tr key={String(row[entity.idKey])}>{columns.map((column)=><td key={column} data-label={entity.fields.find((field)=>field.key===column)?.label??"ID"}>{shown(row[column])}</td>)}{canManage&&<td><div className="ops-row-actions"><button onClick={()=>open(row)}>Edit</button><button className="is-danger" onClick={()=>void remove(row)}>Delete</button></div></td>}</tr>)}{!rows.length&&<tr><td colSpan={columns.length+(canManage?1:0)}><div className="ops-empty"><strong>No records found</strong><span>Adjust the filters or add the first approved record.</span></div></td></tr>}</tbody></table></div><dialog ref={dialog} className="ops-dialog" onClose={()=>setEditing(null)}><form onSubmit={save}><header><div><span>{editing?"Edit":"Create"}</span><h2>{entity.label}</h2></div><button type="button" aria-label="Close dialog" onClick={()=>dialog.current?.close()}>×</button></header><div className="ops-form-grid">{entity.fields.map((field)=><label key={`${String(editing?.[entity.idKey]??"new")}-${field.key}`} className={field.type==="textarea"?"is-wide":""}><span>{field.label}{field.required?" *":""}</span>{field.type==="textarea"?<textarea name={field.key} maxLength={field.max} required={field.required} defaultValue={String(editing?.[field.key]??"")} rows={6}/>:field.type==="select"?<select name={field.key} required={field.required} defaultValue={String(editing?.[field.key]??"")}><option value="">Select…</option>{field.options?.map((option)=><option key={option} value={option}>{option.replaceAll("_"," ")}</option>)}</select>:field.type==="boolean"?<input name={field.key} type="checkbox" defaultChecked={editing?.[field.key]===true}/>:<input name={field.key} type={field.type} required={field.required} maxLength={field.max} defaultValue={String(editing?.[field.key]??"")}/>}</label>)}</div><p role="status">{message}</p><footer><button type="button" onClick={()=>dialog.current?.close()}>Cancel</button><button className="ops-primary">{editing?"Save changes":"Create record"}</button></footer></form></dialog></section>;
}

