import { ApprovedStudentShell } from "@/components/approved-student-shell";

type LockedFeature="dashboard"|"progress"|"documents";

const documentRows=["Passport Front","Passport Back","CV","LoR","UG Marksheet","Degree Certificate","SOP"];

function LockMark(){return <span className="canonical-lock-mark" aria-label="Locked">🔒</span>;}

function LockedProgressBoard(){return <main className="premium-locked-page canonical-progress" data-node-id="17041:14026">
  <section className="pt-6 about-section half-section overlap-height position-relative overflow-hidden mobile-doc-section canonical-progress-hero"><div className="container overlap-gap-section p-0"><div className="row justify-content-md-center align-items-center"><div className="col-lg-7 d-flex gap-10 align-items-center"><div className="w-300px"><h1 className="text-start text-black fnt-family fw-400 fs-50 lh-full pt-0 mb-0">your<br/>custom<br/>progress<br/>board</h1></div><div className="yellow-box-style-3 w-300px canonical-locked-region"><LockMark/><div className="header-yellow-box-style-3">🔔 Important Alerts</div><ol><li>Your mentor&apos;s important updates appear here.</li><li>Deadlines and next steps stay visible.</li></ol></div></div></div></div></section>
  <section className="group-chart-section pt-0 mobile-doc-section canonical-locked-region"><LockMark/><div className="w-780px m-auto"><div className="card-box"><div className="list-of-graphs"><div className="d-flex-group"><p className="mb-0 text-black">#draftMeter</p></div>{["Passport drafts","SOP drafts","CV drafts"].map((label)=><div className="d-flex-group" key={label}><div className="graph-box-content">{label}<span className="blank-dots"/></div></div>)}</div><div className="count-of-grpah"><span>+</span><p className="mb-0 fnt-family fs-100 lh-full">0</p><span>completed</span></div></div><section className="premium-review-notes"><div><h2 className="fnt-family">review queue</h2><article><strong>Your submitted drafts</strong><span>queued</span><p>Mentor review status appears here.</p></article></div><div><h2 className="fnt-family">#counselorNotes</h2><article><p>Student-visible counselor notes appear after Premium activation.</p></article></div></section><section className="premium-kanban" aria-label="Locked custom progress board">{["Draft","In Progress","Completed"].map((title)=><div className="premium-kanban-column" key={title}><h3>{title}</h3><div className="premium-kanban-stack"><article className="card-sm"><h4>Mentor-planned step</h4><p>Your personalized workflow stays locked.</p></article></div></div>)}</section></div></section>
  <section className="canonical-progress-guidance"><h2 className="fnt-family">from first draft to final admit</h2><p>The complete review queue, counselor notes, document meter and shared progress board remain visible as one locked composition.</p></section>
</main>;}

function LockedDocuments({anonymous}:{anonymous:boolean}){return <main className="premium-locked-page canonical-documents" data-node-id={anonymous?"18375:11615":"17041:15941"}><section className="pt-5 about-section half-section overlap-height position-relative overflow-hidden mobile-doc-section"><div className="container overlap-gap-section p-0"><div className="row justify-content-md-center align-items-center"><div className="col-lg-7 d-flex gap-10 align-items-center"><div className="w-300px"><h1 className="text-start text-black fnt-family fw-400 fs-50 lh-full pt-0">upload<br/>your<br/>docs</h1></div><div className="yellow-box-style-3 w-300px canonical-locked-region"><LockMark/><div className="header-yellow-box-style-3">🔔 Important Alerts</div><ol><li>Document requests and review alerts appear here.</li></ol></div></div></div><div className="row justify-content-md-center mt-3"><div className="col-lg-6"><p className="mb-0 text-black fs-19 lh-25"><span className="fs-22 d-block mb-1 fw-500">Secure document access is locked.</span>Premium documents use the private PGS workspace after entitlement activation.</p></div></div><section className="premium-document-group canonical-locked-region"><LockMark/><h2 className="fnt-family">Resource List</h2><div className="premium-document-table-wrap"><table className="w-100 table border-none text-bold-table"><thead><tr><th>Resource Drop</th><th>uploaded on</th><th>qc status</th><th>action</th></tr></thead><tbody>{documentRows.map((label)=><tr key={label}><td>{label}</td><td><span className="blank-dots"/></td><td>Locked</td><td><span className="btn btn-black-upload" aria-disabled="true">Upload</span></td></tr>)}</tbody></table></div></section><section className="premium-document-group canonical-locked-region"><LockMark/><h2 className="fnt-family">Additional documents, if we asked for them</h2><p>Your counselor&apos;s additional requirements appear in this table.</p></section></div></section></main>;}

function LockedDashboard(){return <main className="premium-locked-page canonical-dashboard-locked" data-node-id="17961:10662"><section className="canonical-dashboard-overview canonical-locked-region"><LockMark/><h2>Your Quick Dashboard overview</h2><div className="canonical-metric-grid">{["Uni Applied","Offers Received","Tuition Receipt Uploaded","Visa Applied"].map((label)=><article key={label}><span>{label}</span><strong>—</strong></article>)}</div></section><section className="canonical-dashboard-notes"><article><h2>Notes</h2><p>Your counselor&apos;s roadmap, document feedback and university actions will appear here.</p></article><div><h3>Student pathway</h3><span className="canonical-disabled-action">Track Your Progress</span><span className="canonical-disabled-action">#purpleBoard</span></div></section><section className="canonical-where-you-stand canonical-locked-region"><LockMark/><h2 className="fnt-family">Where You Stand</h2><p>This centralized study dashboard tracks onboarding, milestones, document readiness and university decisions.</p><div className="canonical-prep-grid"><article><strong>0%</strong><span>Through your onboarding journey</span></article><article><h3>Onboarding Checklist</h3><p>Profile · Shortlist · SOP · Tests · Resume · Finance</p></article><article><h3>Documents Tracker</h3><p>Drafts, LORs, certificates and passport</p></article><article><h3>Uni Shortlist</h3><p>Your finalized university list</p></article></div></section></main>;}

export function PremiumLockedState({feature,name,avatarUrl,email="",stateKind="authenticated_standard"}:{feature:LockedFeature;name:string;avatarUrl:string;email?:string;stateKind?:"anonymous"|"authenticated_standard"}){
  const active=feature==="progress"?"progress":feature==="documents"?"documents":"premium";
  return <ApprovedStudentShell name={name} email={email} avatarUrl={avatarUrl} stateKind={stateKind} active={active} contentClassName="approved-workspace-layout">
    {feature==="progress"?<LockedProgressBoard/>:feature==="documents"?<LockedDocuments anonymous={stateKind==="anonymous"}/>:<LockedDashboard/>}
  </ApprovedStudentShell>;
}
