"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

type CatalogItem={id:number;title:string;slug:string;short_description:string};
export type SavedProgram={program_id:number;programs:CatalogItem|null};
export type SavedCourse={course_id:number;courses:CatalogItem|null};

export function SavedList({programs:initialPrograms,courses:initialCourses}:{programs:SavedProgram[];courses:SavedCourse[]}){
  const [programs,setPrograms]=useState(initialPrograms);const [courses,setCourses]=useState(initialCourses);const [status,setStatus]=useState("");
  async function remove(kind:"programs"|"courses",id:number){const response=await fetch(`/api/student/saved/${kind}/${id}`,{method:"DELETE"});if(!response.ok){setStatus("Unable to remove that saved item.");return;}if(kind==="programs")setPrograms((items)=>items.filter((item)=>item.program_id!==id));else setCourses((items)=>items.filter((item)=>item.course_id!==id));setStatus("Removed from saved.");}
  const empty=!programs.length&&!courses.length;
  return <div className="saved-list-pgs canonical-saved-picks">{status&&<p role="status">{status}</p>}{programs.length>0&&<section className="canonical-saved-programs" aria-label="Saved programs">{programs.map((item)=>item.programs&&<article className="sop-card-unique is-program" key={item.program_id}><div className="sop-top-label"><Image src="/assets/img/heart.gif" alt="" width={38} height={38} unoptimized/><span>CV-READY PROGRAM</span></div><div className="sop-image-wrapper"><Image src="/assets/img/saved_4.jpg" alt="" width={420} height={220} unoptimized/><button className="sop-heart-icon" onClick={()=>remove("programs",item.program_id)} aria-label={`Remove ${item.programs?.title}`}>♥</button></div><div className="sop-content"><h2 className="sop-title fnt-family">{item.programs.title}</h2><p className="sop-subtext">{item.programs.short_description}</p><div className="sop-tags"><span className="sop-tag">#CVReady</span><span className="sop-tag">#PGS</span></div><div className="canonical-saved-actions"><Link className="sop-learn-btn" href={`/programsfull/program/${item.programs.id}`}>Learn More</Link><Image src="/assets/img/qr-2.png" alt="Program QR" width={62} height={62} unoptimized/></div></div></article>)}</section>}{courses.length>0&&<section className="canonical-saved-courses" aria-label="Saved courses">{courses.map((item)=>item.courses&&<article className="sop-card-unique" key={item.course_id}><div className="sop-image-wrapper"><Image src="/assets/img/saved_2.jpg" alt="" width={360} height={180} unoptimized/><button className="sop-heart-icon" onClick={()=>remove("courses",item.course_id)} aria-label={`Remove ${item.courses?.title}`}>♥</button></div><div className="sop-content"><h2 className="sop-title fnt-family">{item.courses.title}</h2><p className="sop-subtext">{item.courses.short_description}</p><div className="sop-tags"><span className="sop-tag">#purpleboard</span><span className="sop-tag">#PGS</span></div><Link className="sop-learn-btn" href={`/programsfull/program/${item.courses.id}?type=course`}>Learn More</Link></div></article>)}</section>}{empty&&<div className="pgs-empty-state"><h2>Your saved list is ready</h2><p>Save published courses and programs to find them here.</p><Link href="/cvreadyprogram">Discover programs</Link></div>}</div>;
}
