"use client";

import { useState } from "react";
import type { BoardColumn, DocumentRequirement } from "@/lib/premium-workspace";

export function StaffWorkspaceControls({ studentId, columns, requirements, universities, comments }: { studentId: string; columns: BoardColumn[]; requirements: DocumentRequirement[]; universities: Array<{ id: number; name: string }>; comments: Array<{ id: string; body: string }> }) {
  const [message, setMessage] = useState("");
  async function create(resource: string, values: Record<string, unknown>) {
    setMessage("Saving…");
    const response = await fetch(`/api/staff/students/${studentId}/workspace/${resource}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) });
    const result = await response.json(); if (!response.ok) return setMessage(result.message ?? "Unable to save."); window.location.reload();
  }
  async function update(resource: string, values: Record<string, unknown>) {
    setMessage("Saving…");
    const response = await fetch(`/api/staff/students/${studentId}/workspace/${resource}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(values) });
    const result = await response.json(); if (!response.ok) return setMessage(result.message ?? "Unable to save."); window.location.reload();
  }
  return <section className="staff-workspace-controls"><h2>Workspace actions</h2><p>Changes below use the same student-owned rows shown on the PurpleGuide student workspace.</p><span role="status">{message}</span>
    <details><summary>Update dashboard overview</summary><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void update("profile", { pathway_label: data.get("pathway_label"), intake_label: data.get("intake_label"), universities_applied: Number(data.get("universities_applied")), offers_received: Number(data.get("offers_received")), visa_status: data.get("visa_status") }); }}><input name="pathway_label" placeholder="Pathway" maxLength={120} /><input name="intake_label" placeholder="Intake" maxLength={120} /><input name="universities_applied" type="number" min="0" placeholder="Universities applied" /><input name="offers_received" type="number" min="0" placeholder="Offers" /><input name="visa_status" placeholder="Visa status" maxLength={120} /><button>Update overview</button></form></details>
    <details><summary>Add task</summary><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void create("tasks", { title: data.get("title"), details: data.get("details"), column_id: data.get("column_id"), sort_order: Number(data.get("sort_order")) }); }}><input name="title" placeholder="Task title" required maxLength={255} /><textarea name="details" placeholder="Details" maxLength={6000} /><select name="column_id" required>{columns.map((column) => <option key={column.id} value={column.id}>{column.title}</option>)}</select><input name="sort_order" type="number" min="0" defaultValue="0" /><button>Add task</button></form></details>
    <details><summary>Add student-visible comment or reply</summary><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void create("comments", { body: data.get("body"), visibility: "student_visible", parent_id: data.get("parent_id") || null }); }}><textarea name="body" required maxLength={4000} /><select name="parent_id"><option value="">New comment</option>{comments.map((comment) => <option key={comment.id} value={comment.id}>Reply to: {comment.body.slice(0, 70)}</option>)}</select><button>Post comment</button></form></details>
    <details><summary>Add important alert</summary><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void create("alerts", { alert_text: data.get("alert_text"), severity: data.get("severity") }); }}><textarea name="alert_text" required maxLength={1000} /><select name="severity"><option>important</option><option>urgent</option><option>info</option></select><button>Add alert</button></form></details>
    <details><summary>Add review item</summary><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void create("reviews", { title: data.get("title"), details: data.get("details"), student_visible: true }); }}><input name="title" required maxLength={255} /><textarea name="details" maxLength={4000} /><button>Add review item</button></form></details>
    <details><summary>Add counselor note</summary><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void create("notes", { body: data.get("body"), visibility: data.get("visibility") }); }}><textarea name="body" required maxLength={6000} /><select name="visibility"><option value="staff_only">Staff only (default)</option><option value="student_visible">Visible to student</option></select><button>Add note</button></form></details>
    <details><summary>Request a document</summary><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void create("requirements", { document_type: data.get("document_type"), requirement_kind: "additional", instructions: data.get("instructions") }); }}><input name="document_type" required maxLength={160} /><textarea name="instructions" maxLength={2000} /><button>Add requirement</button></form></details>
    <details><summary>Review uploaded document</summary><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void update("documents", { id: data.get("id"), qc_status: data.get("qc_status"), review_note: data.get("review_note") }); }}><select name="id" required><option value="">Choose document</option>{requirements.flatMap((requirement) => (requirement.student_documents ?? []).map((document) => <option key={document.id} value={document.id}>{requirement.document_type} v{document.version}</option>))}</select><select name="qc_status"><option value="in_review">In review</option><option value="in_draft">In draft</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><textarea name="review_note" maxLength={2000} placeholder="Review note" /><button>Save review</button></form></details>
    <details><summary>Add university selection</summary><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void create("universities", { university_id: Number(data.get("university_id")), stage: data.get("stage") }); }}><select name="university_id" required><option value="">Choose university</option>{universities.map((university) => <option key={university.id} value={university.id}>{university.name}</option>)}</select><select name="stage"><option value="selected">Selected</option><option value="shortlisted">Shortlisted</option><option value="application_started">Application started</option><option value="applied">Applied</option><option value="offer_received">Offer received</option><option value="finalized">Finalized</option></select><button>Add university</button></form></details>
  </section>;
}
