create extension if not exists pg_trgm with schema extensions;
create schema if not exists private;

create table public.cms_pages (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  page_type text not null,
  status text not null default 'draft' check (status in ('draft', 'published', 'unpublished')),
  published_revision_id uuid,
  seo_title text,
  seo_description text,
  open_graph jsonb not null default '{}'::jsonb check (jsonb_typeof(open_graph) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.cms_page_revisions (
  id uuid primary key default gen_random_uuid(),
  page_id uuid not null references public.cms_pages(id) on delete cascade,
  schema_version integer not null default 1 check (schema_version > 0),
  content jsonb not null check (jsonb_typeof(content) = 'object'),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.cms_pages
  add constraint cms_pages_published_revision_fk
  foreign key (published_revision_id) references public.cms_page_revisions(id) on delete set null;

create table public.media_assets (
  id uuid primary key default gen_random_uuid(),
  bucket text not null check (bucket in ('marketing-public', 'cms-previews')),
  path text not null,
  alt_text text not null default '',
  mime_type text not null,
  byte_size bigint not null check (byte_size >= 0),
  width integer check (width is null or width > 0),
  height integer check (height is null or height > 0),
  attribution text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique (bucket, path)
);

create table public.countries (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  name text not null,
  slug text not null unique,
  iso_code text,
  dial_code text,
  published boolean not null default false,
  display_order integer not null default 0
);

create table public.universities (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  country_id bigint references public.countries(id) on delete set null,
  name text not null,
  slug text not null unique,
  summary text not null default '',
  image_asset_id uuid references public.media_assets(id) on delete set null,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.programs (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  university_id bigint references public.universities(id) on delete set null,
  title text not null,
  slug text not null unique,
  short_description text not null default '',
  description text not null default '',
  brochure_asset_id uuid references public.media_assets(id) on delete set null,
  image_asset_id uuid references public.media_assets(id) on delete set null,
  published boolean not null default false,
  featured boolean not null default false,
  display_order integer not null default 0,
  search_document text generated always as (title || ' ' || short_description || ' ' || description) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.course_categories (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  name text not null,
  slug text not null unique,
  published boolean not null default false,
  display_order integer not null default 0
);

create table public.courses (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  category_id bigint references public.course_categories(id) on delete set null,
  university_id bigint references public.universities(id) on delete set null,
  title text not null,
  slug text not null unique,
  short_description text not null default '',
  description text not null default '',
  image_asset_id uuid references public.media_assets(id) on delete set null,
  published boolean not null default false,
  featured boolean not null default false,
  search_document text generated always as (title || ' ' || short_description || ' ' || description) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.event_categories (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  name text not null,
  slug text not null unique,
  published boolean not null default false
);

create table public.events (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  category_id bigint references public.event_categories(id) on delete set null,
  title text not null,
  slug text not null unique,
  summary text not null default '',
  description text not null default '',
  starts_at timestamptz,
  ends_at timestamptz,
  booking_url text,
  image_asset_id uuid references public.media_assets(id) on delete set null,
  published boolean not null default false,
  search_document text generated always as (title || ' ' || summary || ' ' || description) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or starts_at is null or ends_at >= starts_at)
);

create table public.event_facilitators (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  event_id bigint not null references public.events(id) on delete cascade,
  name text not null,
  role text not null default '',
  biography text not null default '',
  image_asset_id uuid references public.media_assets(id) on delete set null,
  display_order integer not null default 0
);

create table public.catalog_tags (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  tag_type text not null default 'topic',
  published boolean not null default false
);

create table public.program_tags (
  program_id bigint not null references public.programs(id) on delete cascade,
  tag_id bigint not null references public.catalog_tags(id) on delete cascade,
  primary key (program_id, tag_id)
);

create table public.course_tags (
  course_id bigint not null references public.courses(id) on delete cascade,
  tag_id bigint not null references public.catalog_tags(id) on delete cascade,
  primary key (course_id, tag_id)
);

create table public.event_tags (
  event_id bigint not null references public.events(id) on delete cascade,
  tag_id bigint not null references public.catalog_tags(id) on delete cascade,
  primary key (event_id, tag_id)
);

create table public.catalog_filter_facets (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('program', 'course', 'event', 'university')),
  name text not null,
  slug text not null,
  display_order integer not null default 0,
  unique (entity_type, slug)
);

create table public.catalog_filter_options (
  id bigint generated by default as identity primary key,
  facet_id bigint not null references public.catalog_filter_facets(id) on delete cascade,
  label text not null,
  value text not null,
  display_order integer not null default 0,
  unique (facet_id, value)
);

create table public.program_filter_options (
  program_id bigint not null references public.programs(id) on delete cascade,
  option_id bigint not null references public.catalog_filter_options(id) on delete cascade,
  primary key (program_id, option_id)
);

create table public.course_filter_options (
  course_id bigint not null references public.courses(id) on delete cascade,
  option_id bigint not null references public.catalog_filter_options(id) on delete cascade,
  primary key (course_id, option_id)
);

create table public.event_filter_options (
  event_id bigint not null references public.events(id) on delete cascade,
  option_id bigint not null references public.catalog_filter_options(id) on delete cascade,
  primary key (event_id, option_id)
);

create table public.university_filter_options (
  university_id bigint not null references public.universities(id) on delete cascade,
  option_id bigint not null references public.catalog_filter_options(id) on delete cascade,
  primary key (university_id, option_id)
);

create table public.faqs (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  scope text not null,
  question text not null,
  answer text not null,
  published boolean not null default false,
  display_order integer not null default 0
);

create table public.weekly_wall_items (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  title text not null,
  body text not null,
  published boolean not null default false,
  display_order integer not null default 0
);

create table public.key_dates (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  title text not null,
  date_value date,
  month_label text,
  published boolean not null default false,
  display_order integer not null default 0
);

create table public.urgent_deadlines (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  title text not null,
  deadline date,
  url text,
  published boolean not null default false,
  display_order integer not null default 0
);

create table public.study_abroad_facts (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  fact text not null,
  published boolean not null default false,
  display_order integer not null default 0
);

create table public.pgs_stats (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  category text not null,
  label text not null,
  value text not null,
  published boolean not null default false,
  display_order integer not null default 0
);

create table public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 160),
  email text not null default '' check (char_length(email) <= 254),
  phone text not null default '' check (char_length(phone) <= 40),
  message text not null default '' check (char_length(message) <= 4000),
  source_page text not null check (char_length(source_page) <= 120),
  status text not null default 'new' check (status in ('new', 'in_progress', 'closed')),
  created_at timestamptz not null default now(),
  check (email <> '' or phone <> '')
);

create table public.lead_submissions (
  id bigint generated by default as identity primary key,
  submission_type text not null check (char_length(submission_type) <= 120),
  name text not null default '' check (char_length(name) <= 160),
  email text not null default '' check (char_length(email) <= 254),
  phone text not null default '' check (char_length(phone) <= 40),
  source_page text not null check (char_length(source_page) <= 120),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  status text not null default 'new' check (status in ('new', 'in_progress', 'closed')),
  created_at timestamptz not null default now(),
  check (email <> '' or phone <> '')
);

create table public.study_journey_enquiries (
  id bigint generated by default as identity primary key,
  name text not null default '' check (char_length(name) <= 160),
  email text not null default '' check (char_length(email) <= 254),
  phone text not null default '' check (char_length(phone) <= 40),
  source_page text not null check (char_length(source_page) <= 120),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  status text not null default 'new' check (status in ('new', 'in_progress', 'closed')),
  created_at timestamptz not null default now(),
  check (email <> '' or phone <> '')
);

create table public.deadline_subscriptions (
  id bigint generated by default as identity primary key,
  email text not null check (char_length(email) between 3 and 254),
  source_page text not null check (char_length(source_page) <= 120),
  status text not null default 'active' check (status in ('active', 'unsubscribed')),
  created_at timestamptz not null default now(),
  unique (email)
);

create table private.integration_outbox (
  id bigint generated by default as identity primary key,
  event_type text not null,
  entity_table text not null,
  entity_id text not null,
  deduplication_key text not null unique,
  status text not null default 'pending' check (status in ('pending', 'processing', 'sent', 'failed', 'disabled')),
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index programs_search_idx on public.programs using gin (search_document extensions.gin_trgm_ops);
create index courses_search_idx on public.courses using gin (search_document extensions.gin_trgm_ops);
create index events_search_idx on public.events using gin (search_document extensions.gin_trgm_ops);
create index events_starts_at_idx on public.events (starts_at) where published;

create or replace function private.queue_public_submission()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into private.integration_outbox (event_type, entity_table, entity_id, deduplication_key, status)
  values ('public_submission.created', tg_table_name, new.id::text, tg_table_name || ':' || new.id::text, 'disabled');
  return new;
end;
$$;

create trigger queue_enquiry after insert on public.enquiries for each row execute function private.queue_public_submission();
create trigger queue_lead_submission after insert on public.lead_submissions for each row execute function private.queue_public_submission();
create trigger queue_study_journey after insert on public.study_journey_enquiries for each row execute function private.queue_public_submission();
create trigger queue_deadline_subscription after insert on public.deadline_subscriptions for each row execute function private.queue_public_submission();

create or replace function public.publish_cms_revision(target_page uuid, target_revision uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (select 1 from public.cms_editors where user_id = auth.uid()) then
    raise exception 'not authorized';
  end if;
  if not exists (select 1 from public.cms_page_revisions where id = target_revision and page_id = target_page) then
    raise exception 'revision does not belong to page';
  end if;
  update public.cms_pages
  set published_revision_id = target_revision, status = 'published', updated_at = now()
  where id = target_page;
end;
$$;

alter table public.cms_pages enable row level security;
alter table public.cms_page_revisions enable row level security;
alter table public.media_assets enable row level security;
alter table public.countries enable row level security;
alter table public.universities enable row level security;
alter table public.programs enable row level security;
alter table public.course_categories enable row level security;
alter table public.courses enable row level security;
alter table public.event_categories enable row level security;
alter table public.events enable row level security;
alter table public.event_facilitators enable row level security;
alter table public.catalog_tags enable row level security;
alter table public.program_tags enable row level security;
alter table public.course_tags enable row level security;
alter table public.event_tags enable row level security;
alter table public.catalog_filter_facets enable row level security;
alter table public.catalog_filter_options enable row level security;
alter table public.program_filter_options enable row level security;
alter table public.course_filter_options enable row level security;
alter table public.event_filter_options enable row level security;
alter table public.university_filter_options enable row level security;
alter table public.faqs enable row level security;
alter table public.weekly_wall_items enable row level security;
alter table public.key_dates enable row level security;
alter table public.urgent_deadlines enable row level security;
alter table public.study_abroad_facts enable row level security;
alter table public.pgs_stats enable row level security;
alter table public.enquiries enable row level security;
alter table public.lead_submissions enable row level security;
alter table public.study_journey_enquiries enable row level security;
alter table public.deadline_subscriptions enable row level security;

create policy "public reads published cms pages" on public.cms_pages for select to anon, authenticated using (status = 'published');
create policy "editors manage cms pages" on public.cms_pages for all to authenticated using (exists (select 1 from public.cms_editors where user_id = (select auth.uid()))) with check (exists (select 1 from public.cms_editors where user_id = (select auth.uid())));
create policy "public reads published cms revisions" on public.cms_page_revisions for select to anon, authenticated using (exists (select 1 from public.cms_pages where cms_pages.published_revision_id = cms_page_revisions.id and cms_pages.status = 'published'));
create policy "editors create cms revisions" on public.cms_page_revisions for insert to authenticated with check (created_by = (select auth.uid()) and exists (select 1 from public.cms_editors where user_id = (select auth.uid())));
create policy "editors read cms revisions" on public.cms_page_revisions for select to authenticated using (exists (select 1 from public.cms_editors where user_id = (select auth.uid())));
create policy "public reads marketing media" on public.media_assets for select to anon, authenticated using (bucket = 'marketing-public');
create policy "editors manage media metadata" on public.media_assets for all to authenticated using (exists (select 1 from public.cms_editors where user_id = (select auth.uid()))) with check (exists (select 1 from public.cms_editors where user_id = (select auth.uid())));

create policy "public reads countries" on public.countries for select to anon, authenticated using (published);
create policy "public reads universities" on public.universities for select to anon, authenticated using (published);
create policy "public reads programs" on public.programs for select to anon, authenticated using (published);
create policy "public reads course categories" on public.course_categories for select to anon, authenticated using (published);
create policy "public reads courses" on public.courses for select to anon, authenticated using (published);
create policy "public reads event categories" on public.event_categories for select to anon, authenticated using (published);
create policy "public reads events" on public.events for select to anon, authenticated using (published);
create policy "public reads event facilitators" on public.event_facilitators for select to anon, authenticated using (exists (select 1 from public.events where events.id = event_facilitators.event_id and events.published));
create policy "public reads catalog tags" on public.catalog_tags for select to anon, authenticated using (published);
create policy "public reads program tags" on public.program_tags for select to anon, authenticated using (exists (select 1 from public.programs where programs.id = program_tags.program_id and programs.published));
create policy "public reads course tags" on public.course_tags for select to anon, authenticated using (exists (select 1 from public.courses where courses.id = course_tags.course_id and courses.published));
create policy "public reads event tags" on public.event_tags for select to anon, authenticated using (exists (select 1 from public.events where events.id = event_tags.event_id and events.published));
create policy "public reads catalog facets" on public.catalog_filter_facets for select to anon, authenticated using (true);
create policy "public reads catalog options" on public.catalog_filter_options for select to anon, authenticated using (true);
create policy "public reads program filter options" on public.program_filter_options for select to anon, authenticated using (exists (select 1 from public.programs where programs.id = program_filter_options.program_id and programs.published));
create policy "public reads course filter options" on public.course_filter_options for select to anon, authenticated using (exists (select 1 from public.courses where courses.id = course_filter_options.course_id and courses.published));
create policy "public reads event filter options" on public.event_filter_options for select to anon, authenticated using (exists (select 1 from public.events where events.id = event_filter_options.event_id and events.published));
create policy "public reads university filter options" on public.university_filter_options for select to anon, authenticated using (exists (select 1 from public.universities where universities.id = university_filter_options.university_id and universities.published));
create policy "public reads faqs" on public.faqs for select to anon, authenticated using (published);
create policy "public reads weekly wall" on public.weekly_wall_items for select to anon, authenticated using (published);
create policy "public reads key dates" on public.key_dates for select to anon, authenticated using (published);
create policy "public reads urgent deadlines" on public.urgent_deadlines for select to anon, authenticated using (published);
create policy "public reads study facts" on public.study_abroad_facts for select to anon, authenticated using (published);
create policy "public reads pgs stats" on public.pgs_stats for select to anon, authenticated using (published);

create policy "public submits enquiries" on public.enquiries for insert to anon, authenticated with check (status = 'new');
create policy "public submits leads" on public.lead_submissions for insert to anon, authenticated with check (status = 'new');
create policy "public submits study journeys" on public.study_journey_enquiries for insert to anon, authenticated with check (status = 'new');
create policy "public subscribes to deadlines" on public.deadline_subscriptions for insert to anon, authenticated with check (status = 'active');

revoke all on public.cms_pages, public.cms_page_revisions, public.media_assets,
  public.countries, public.universities, public.programs, public.course_categories, public.courses,
  public.event_categories, public.events, public.event_facilitators, public.catalog_tags, public.program_tags,
  public.course_tags, public.event_tags, public.catalog_filter_facets, public.catalog_filter_options,
  public.program_filter_options, public.course_filter_options, public.event_filter_options, public.university_filter_options,
  public.faqs, public.weekly_wall_items,
  public.key_dates, public.urgent_deadlines, public.study_abroad_facts, public.pgs_stats,
  public.enquiries, public.lead_submissions, public.study_journey_enquiries, public.deadline_subscriptions
from anon, authenticated;
grant select on public.cms_pages, public.cms_page_revisions, public.media_assets to anon, authenticated;
grant select on public.countries, public.universities, public.programs, public.course_categories, public.courses, public.event_categories, public.events, public.event_facilitators, public.faqs, public.weekly_wall_items, public.key_dates, public.urgent_deadlines, public.study_abroad_facts, public.pgs_stats to anon, authenticated;
grant select on public.catalog_tags, public.program_tags, public.course_tags, public.event_tags, public.catalog_filter_facets, public.catalog_filter_options, public.program_filter_options, public.course_filter_options, public.event_filter_options, public.university_filter_options to anon, authenticated;
grant insert on public.enquiries, public.lead_submissions, public.study_journey_enquiries, public.deadline_subscriptions to anon, authenticated;
grant insert, update, select on public.cms_pages to authenticated;
grant insert, select on public.cms_page_revisions to authenticated;
grant insert, update, delete, select on public.media_assets to authenticated;
grant usage, select on sequence public.enquiries_id_seq, public.lead_submissions_id_seq,
  public.study_journey_enquiries_id_seq, public.deadline_subscriptions_id_seq to anon, authenticated;
grant execute on function public.publish_cms_revision(uuid, uuid) to authenticated;

insert into public.cms_pages (slug, page_type)
select slug, page_type from (values
  ('about', 'about'), ('contact', 'contact'), ('countriesaus', 'destination'),
  ('countriescanada', 'destination'), ('countrieseurope', 'destination'), ('countriesfrance', 'destination'),
  ('countriesgermany', 'destination'), ('countriesmauritius', 'destination'), ('countriesnz', 'destination'),
  ('countriesothers', 'destination'), ('countriesuk', 'destination'), ('cvreadyprogram', 'program-listing'),
  ('explorecountries', 'destination-discovery'), ('finance', 'finance'), ('forgot-password', 'auth'),
  ('login', 'auth'), ('program-detail', 'program-detail'), ('purpleamc', 'pathway'),
  ('purpleboard', 'course-listing'), ('purpleevents', 'event-listing'), ('purpleevents-session', 'event-detail'),
  ('purplenonmedical', 'pathway'), ('purpleplab', 'pathway'), ('purplepremiumhome', 'premium-landing'),
  ('purpleusme', 'pathway'), ('scholarship', 'scholarship'), ('simplehome', 'home-variant'),
  ('signup', 'auth'), ('studentresources', 'student-resources'), ('unitieup', 'university-partnership'),
  ('usmlerotation', 'rotation'), ('reset-password', 'auth'), ('change-password', 'auth'),
  ('error-404', 'error')
) as pages(slug, page_type)
on conflict (slug) do nothing;
