-- Batch 4 completion: active audited content and lead-triage domains absent from 001.

create table public.article_categories (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 160),
  slug text not null unique check (char_length(slug) between 1 and 180),
  published boolean not null default false,
  display_order integer not null default 0 check (display_order >= 0)
);
create table public.articles (
  id bigint generated by default as identity primary key,
  category_id bigint references public.article_categories(id) on delete set null,
  title text not null check (char_length(title) between 1 and 300),
  slug text not null unique check (char_length(slug) between 1 and 320),
  summary text not null default '' check (char_length(summary) <= 3000),
  body text not null default '' check (char_length(body) <= 100000),
  layout_key text not null default 'standard' check (layout_key in ('standard','feature','guide')),
  image_asset_id uuid references public.media_assets(id) on delete set null,
  featured boolean not null default false,
  published boolean not null default false,
  display_order integer not null default 0 check (display_order >= 0),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.highlights (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 300),
  body text not null default '' check (char_length(body) <= 6000),
  image_asset_id uuid references public.media_assets(id) on delete set null,
  published boolean not null default false,
  display_order integer not null default 0 check (display_order >= 0),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.lead_triage_notes (
  id uuid primary key default gen_random_uuid(),
  lead_table text not null check (lead_table in ('enquiries','lead_submissions','study_journey_enquiries','deadline_subscriptions')),
  lead_id bigint not null,
  body text not null check (char_length(body) between 1 and 4000),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);
create index lead_triage_notes_target_idx on public.lead_triage_notes(lead_table,lead_id,created_at desc);

alter table public.article_categories enable row level security;
alter table public.articles enable row level security;
alter table public.highlights enable row level security;
alter table public.lead_triage_notes enable row level security;

create policy "public reads article categories" on public.article_categories for select to anon,authenticated using(published);
create policy "public reads articles" on public.articles for select to anon,authenticated using(published);
create policy "public reads highlights" on public.highlights for select to anon,authenticated using(published);
create policy "staff read article categories" on public.article_categories for select to authenticated using(private.has_staff_permission('content.read'));
create policy "staff manage article categories" on public.article_categories for all to authenticated using(private.has_staff_permission('content.manage')) with check(private.has_staff_permission('content.manage'));
create policy "staff read articles" on public.articles for select to authenticated using(private.has_staff_permission('content.read'));
create policy "staff manage articles" on public.articles for all to authenticated using(private.has_staff_permission('content.manage')) with check(private.has_staff_permission('content.manage'));
create policy "staff read highlights" on public.highlights for select to authenticated using(private.has_staff_permission('content.read'));
create policy "staff manage highlights" on public.highlights for all to authenticated using(private.has_staff_permission('content.manage')) with check(private.has_staff_permission('content.manage'));
create policy "staff read lead notes" on public.lead_triage_notes for select to authenticated using(private.has_staff_permission('leads.read'));
create policy "staff create lead notes" on public.lead_triage_notes for insert to authenticated with check(private.has_staff_permission('leads.manage') and created_by=auth.uid());

-- Student-directory readers may inspect assignment state but still cannot mutate it.
create policy "student directory readers inspect assignments" on public.mentor_assignments for select to authenticated using(private.has_staff_permission('students.read'));
create policy "audit readers inspect premium audit" on public.premium_audit_logs for select to authenticated using(private.has_staff_permission('audit.read'));

create or replace function private.audit_admin_change()
returns trigger language plpgsql security definer set search_path = '' as $$
declare before_row jsonb; after_row jsonb; payload jsonb; entity text;
begin
  before_row := case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else '{}'::jsonb end;
  after_row := case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else '{}'::jsonb end;
  payload := case when tg_op = 'DELETE' then before_row else after_row end;
  entity := coalesce(payload->>'id',payload->>'slug',payload->>'key',payload->>'user_id',payload->>'student_id');
  insert into public.admin_audit_logs(actor_id,action,domain,entity_type,entity_id,old_values,new_values)
  values(auth.uid(),lower(tg_op),case
    when tg_table_name in ('cms_pages','cms_page_revisions','media_assets') then 'cms'
    when tg_table_name in ('enquiries','lead_submissions','study_journey_enquiries','deadline_subscriptions','lead_triage_notes') then 'leads'
    when tg_table_name in ('staff_profiles','staff_role_assignments') then 'staff'
    when tg_table_name = 'site_settings' then 'settings'
    when tg_table_name in ('faqs','weekly_wall_items','key_dates','urgent_deadlines','study_abroad_facts','pgs_stats','testimonials','content_people','site_notices','legal_documents','site_social_links','university_meeting_slots','premium_content_settings','article_categories','articles','highlights') then 'content'
    else 'catalog' end,tg_table_name,entity,before_row,after_row);
  if tg_op='DELETE' then return old; end if; return new;
end;
$$;

create trigger audit_article_categories_admin after insert or update or delete on public.article_categories for each row execute function private.audit_admin_change();
create trigger audit_articles_admin after insert or update or delete on public.articles for each row execute function private.audit_admin_change();
create trigger audit_highlights_admin after insert or update or delete on public.highlights for each row execute function private.audit_admin_change();
create trigger audit_lead_triage_notes_admin after insert or update or delete on public.lead_triage_notes for each row execute function private.audit_admin_change();

revoke all on public.article_categories,public.articles,public.highlights,public.lead_triage_notes from anon,authenticated;
grant select on public.article_categories,public.articles,public.highlights to anon,authenticated;
grant insert,update,delete on public.article_categories,public.articles,public.highlights to authenticated;
grant select,insert on public.lead_triage_notes to authenticated;
grant usage,select on sequence public.article_categories_id_seq,public.articles_id_seq,public.highlights_id_seq to authenticated;
