-- Batch 4: normalized staff authorization and internal operations.
-- Applied migrations 001-003 remain immutable. Premium is not a staff role.

alter table public.staff_profiles drop constraint if exists staff_profiles_role_check;
alter table public.staff_profiles add constraint staff_profiles_role_check
  check (role in ('mentor', 'admin', 'super_admin', 'viewer'));

create table public.staff_roles (
  id uuid primary key default gen_random_uuid(),
  key text not null unique check (key in ('super_admin', 'admin', 'mentor', 'viewer')),
  label text not null check (char_length(label) between 1 and 80),
  description text not null default '' check (char_length(description) <= 500),
  system_role boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.staff_permissions (
  id bigint generated by default as identity primary key,
  key text not null unique check (key ~ '^[a-z][a-z0-9_.]{2,79}$'),
  label text not null check (char_length(label) between 1 and 120),
  domain text not null check (char_length(domain) between 1 and 60),
  description text not null default '' check (char_length(description) <= 500)
);

create table public.staff_role_permissions (
  role_id uuid not null references public.staff_roles(id) on delete cascade,
  permission_id bigint not null references public.staff_permissions(id) on delete cascade,
  primary key (role_id, permission_id)
);

create table public.staff_role_assignments (
  id uuid primary key default gen_random_uuid(),
  staff_user_id uuid not null references public.staff_profiles(user_id) on delete cascade,
  role_id uuid not null references public.staff_roles(id) on delete restrict,
  assigned_by uuid references auth.users(id) on delete set null,
  assigned_at timestamptz not null default now(),
  revoked_by uuid references auth.users(id) on delete set null,
  revoked_at timestamptz,
  reason text check (reason is null or char_length(reason) <= 1000),
  check ((revoked_at is null and revoked_by is null) or (revoked_at is not null and revoked_by is not null))
);
create unique index staff_role_assignments_active_idx on public.staff_role_assignments(staff_user_id, role_id) where revoked_at is null;
create index staff_role_assignments_user_idx on public.staff_role_assignments(staff_user_id, assigned_at desc);

insert into public.staff_roles(key,label,description) values
  ('super_admin','Super Admin','All approved operational and staff-governance permissions.'),
  ('admin','Admin','Day-to-day student, catalog, content, lead, and CMS operations.'),
  ('mentor','Mentor / Counselor','Assigned-student workspace operations only.'),
  ('viewer','Viewer','Explicitly permitted read-only operational access.')
on conflict (key) do update set label = excluded.label, description = excluded.description;

insert into public.staff_permissions(key,label,domain,description) values
  ('overview.read','View overview','overview','View internal operational summaries.'),
  ('students.read','View students','students','View the operational student directory.'),
  ('student_workspace.read','View assigned workspaces','students','View assigned student workspaces.'),
  ('student_workspace.read_all','View all workspaces','students','View all Premium student workspaces.'),
  ('student_workspace.manage','Manage assigned workspaces','students','Mutate permitted assigned-student workflow data.'),
  ('student_workspace.manage_all','Manage all workspaces','students','Mutate permitted workflow data for all students.'),
  ('premium.manage','Manage Premium','premium','Grant, revoke, and reactivate Premium.'),
  ('mentor_assignments.manage','Manage mentor assignments','students','Assign, replace, and end mentor assignments.'),
  ('catalog.read','View catalog','catalog','View draft and published catalog records.'),
  ('catalog.manage','Manage catalog','catalog','Create, update, relate, order, and delete catalog records.'),
  ('catalog.publish','Publish catalog','catalog','Publish or unpublish catalog records.'),
  ('cms.read','View CMS','content','View CMS pages, drafts, previews, and revision history.'),
  ('cms.manage','Manage CMS drafts','content','Create pages and validated revisions.'),
  ('cms.publish','Publish CMS','content','Publish, unpublish, and roll back CMS revisions.'),
  ('content.read','View content modules','content','View structured content modules.'),
  ('content.manage','Manage content modules','content','Create, update, order, and delete structured content.'),
  ('content.publish','Publish content modules','content','Publish or unpublish structured content.'),
  ('media.read','View media','content','View marketing and CMS-preview media.'),
  ('media.manage','Manage media','content','Upload and manage approved public/preview media.'),
  ('leads.read','View leads','leads','View public enquiries and subscriptions.'),
  ('leads.manage','Triage leads','leads','Change lead status and operational notes.'),
  ('staff.read','View staff','staff','View staff identities, roles, and status.'),
  ('roles.manage','Manage staff roles','staff','Create staff access, assign/revoke roles, and activate/deactivate staff.'),
  ('audit.read','View audit','audit','Inspect protected operational and security audit events.'),
  ('settings.read','View settings','settings','View internal site and integration settings.'),
  ('settings.manage','Manage settings','settings','Change approved internal settings.')
on conflict (key) do update set label = excluded.label, domain = excluded.domain, description = excluded.description;

-- Super Admin receives every permission. Admin excludes role governance. Mentor is
-- assignment-scoped. Viewer receives only the explicitly listed read permissions.
insert into public.staff_role_permissions(role_id, permission_id)
select r.id, p.id from public.staff_roles r cross join public.staff_permissions p where r.key = 'super_admin'
on conflict do nothing;
insert into public.staff_role_permissions(role_id, permission_id)
select r.id, p.id from public.staff_roles r join public.staff_permissions p on p.key in (
  'overview.read','students.read','student_workspace.read_all','student_workspace.manage_all','premium.manage',
  'mentor_assignments.manage','catalog.read','catalog.manage','catalog.publish','cms.read','cms.manage','cms.publish',
  'content.read','content.manage','content.publish','media.read','media.manage','leads.read','leads.manage',
  'staff.read','audit.read','settings.read','settings.manage'
) where r.key = 'admin' on conflict do nothing;
insert into public.staff_role_permissions(role_id, permission_id)
select r.id, p.id from public.staff_roles r join public.staff_permissions p on p.key in (
  'overview.read','student_workspace.read','student_workspace.manage','media.read'
) where r.key = 'mentor' on conflict do nothing;
insert into public.staff_role_permissions(role_id, permission_id)
select r.id, p.id from public.staff_roles r join public.staff_permissions p on p.key in (
  'overview.read','students.read','catalog.read','cms.read','content.read','media.read','leads.read','settings.read'
) where r.key = 'viewer' on conflict do nothing;

-- Preserve every Batch 3 staff identity while moving authorization to assignments.
insert into public.staff_role_assignments(staff_user_id, role_id, assigned_by, reason)
select sp.user_id, sr.id, sp.created_by, 'Batch 4 normalized-role backfill'
from public.staff_profiles sp join public.staff_roles sr on sr.key = sp.role
on conflict (staff_user_id, role_id) where revoked_at is null do nothing;

create or replace function private.has_staff_permission(permission_key text)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.staff_profiles sp
    join public.staff_role_assignments a on a.staff_user_id = sp.user_id and a.revoked_at is null
    join public.staff_role_permissions rp on rp.role_id = a.role_id
    join public.staff_permissions p on p.id = rp.permission_id
    where sp.user_id = auth.uid() and sp.status = 'active' and p.key = permission_key
  )
$$;
revoke all on function private.has_staff_permission(text) from public;
grant execute on function private.has_staff_permission(text) to authenticated;

create or replace function private.current_staff_role()
returns text language sql stable security definer set search_path = '' as $$
  select r.key from public.staff_profiles sp
  join public.staff_role_assignments a on a.staff_user_id = sp.user_id and a.revoked_at is null
  join public.staff_roles r on r.id = a.role_id
  where sp.user_id = auth.uid() and sp.status = 'active'
  order by case r.key when 'super_admin' then 1 when 'admin' then 2 when 'mentor' then 3 else 4 end limit 1
$$;

create or replace function private.is_privileged_staff()
returns boolean language sql stable security definer set search_path = '' as $$
  select private.has_staff_permission('student_workspace.read_all')
$$;

create or replace function private.is_active_mentor(target_student uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select private.has_staff_permission('student_workspace.read') and exists (
    select 1 from public.mentor_assignments a
    where a.student_id = target_student and a.mentor_id = auth.uid() and a.status = 'active'
  )
$$;

create or replace function private.can_access_premium_student(target_student uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select private.has_active_premium(target_student) and (
    auth.uid() = target_student or private.is_active_mentor(target_student)
    or private.has_staff_permission('student_workspace.read_all')
  )
$$;

create table public.admin_audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references auth.users(id) on delete set null,
  action text not null check (char_length(action) between 1 and 120),
  domain text not null check (char_length(domain) between 1 and 80),
  entity_type text not null check (char_length(entity_type) between 1 and 100),
  entity_id text check (entity_id is null or char_length(entity_id) <= 255),
  target_user_id uuid references auth.users(id) on delete set null,
  old_values jsonb not null default '{}'::jsonb check (jsonb_typeof(old_values) = 'object'),
  new_values jsonb not null default '{}'::jsonb check (jsonb_typeof(new_values) = 'object'),
  reason text check (reason is null or char_length(reason) <= 1000),
  created_at timestamptz not null default now()
);
create index admin_audit_created_idx on public.admin_audit_logs(created_at desc);
create index admin_audit_actor_idx on public.admin_audit_logs(actor_id, created_at desc);
create index admin_audit_entity_idx on public.admin_audit_logs(entity_type, entity_id, created_at desc);

create or replace function private.audit_admin_change()
returns trigger language plpgsql security definer set search_path = '' as $$
declare before_row jsonb; after_row jsonb; payload jsonb; entity text;
begin
  before_row := case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else '{}'::jsonb end;
  after_row := case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else '{}'::jsonb end;
  payload := case when tg_op = 'DELETE' then before_row else after_row end;
  entity := coalesce(payload->>'id', payload->>'slug', payload->>'key', payload->>'user_id', payload->>'student_id');
  insert into public.admin_audit_logs(actor_id,action,domain,entity_type,entity_id,old_values,new_values)
  values(auth.uid(),lower(tg_op),case
    when tg_table_name in ('cms_pages','cms_page_revisions','media_assets') then 'cms'
    when tg_table_name in ('enquiries','lead_submissions','study_journey_enquiries','deadline_subscriptions') then 'leads'
    when tg_table_name in ('staff_profiles','staff_role_assignments') then 'staff'
    when tg_table_name in ('site_settings') then 'settings'
    when tg_table_name in ('faqs','weekly_wall_items','key_dates','urgent_deadlines','study_abroad_facts','pgs_stats','testimonials','content_people','site_notices','legal_documents','site_social_links','university_meeting_slots','premium_content_settings') then 'content'
    else 'catalog' end,
    tg_table_name,entity,before_row,after_row);
  if tg_op = 'DELETE' then return old; end if; return new;
end;
$$;

create table public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 160),
  quote text not null check (char_length(quote) between 1 and 4000),
  role_label text not null default '' check (char_length(role_label) <= 160),
  image_asset_id uuid references public.media_assets(id) on delete set null,
  published boolean not null default false,
  display_order integer not null default 0 check (display_order >= 0),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.content_people (
  id bigint generated by default as identity primary key,
  person_type text not null check (person_type in ('founder','advisory')),
  name text not null check (char_length(name) between 1 and 160),
  title text not null default '' check (char_length(title) <= 200),
  biography text not null default '' check (char_length(biography) <= 12000),
  image_asset_id uuid references public.media_assets(id) on delete set null,
  published boolean not null default false,
  display_order integer not null default 0 check (display_order >= 0),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.site_notices (
  id bigint generated by default as identity primary key,
  notice_type text not null default 'marquee' check (notice_type in ('marquee','banner','maintenance')),
  text text not null check (char_length(text) between 1 and 1000),
  link_url text check (link_url is null or char_length(link_url) <= 1000),
  active boolean not null default false,
  starts_at timestamptz, ends_at timestamptz,
  display_order integer not null default 0 check (display_order >= 0),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  check (ends_at is null or starts_at is null or ends_at >= starts_at)
);
create table public.legal_documents (
  id uuid primary key default gen_random_uuid(),
  document_type text not null unique check (document_type in ('privacy','terms','refund')),
  title text not null check (char_length(title) between 1 and 200),
  body text not null default '' check (char_length(body) <= 100000),
  status text not null default 'draft' check (status in ('draft','published','unpublished')),
  version integer not null default 1 check (version > 0),
  published_at timestamptz,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.site_social_links (
  id bigint generated by default as identity primary key,
  platform text not null unique check (char_length(platform) between 1 and 80),
  url text not null check (char_length(url) between 1 and 1000),
  published boolean not null default false,
  display_order integer not null default 0 check (display_order >= 0)
);
create table public.university_meeting_slots (
  id bigint generated by default as identity primary key,
  label text not null check (char_length(label) between 1 and 160),
  starts_at timestamptz,
  course_id bigint references public.courses(id) on delete set null,
  booking_url text check (booking_url is null or char_length(booking_url) <= 1000),
  published boolean not null default false,
  display_order integer not null default 0 check (display_order >= 0)
);
create table public.premium_content_settings (
  key text primary key check (key in ('video','meetup')),
  title text not null default '' check (char_length(title) <= 240),
  body text not null default '' check (char_length(body) <= 4000),
  media_asset_id uuid references public.media_assets(id) on delete set null,
  link_url text check (link_url is null or char_length(link_url) <= 1000),
  published boolean not null default false,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);
create table public.site_settings (
  key text primary key check (key ~ '^[a-z][a-z0-9_.]{2,99}$'),
  value jsonb not null default '{}'::jsonb,
  description text not null default '' check (char_length(description) <= 500),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

alter table public.cms_page_revisions add column revision_note text check (revision_note is null or char_length(revision_note) <= 500);

create or replace function public.publish_cms_revision(target_page uuid, target_revision uuid)
returns void language plpgsql security definer set search_path = '' as $$
declare old_page jsonb;
begin
  if not private.has_staff_permission('cms.publish') then raise exception 'forbidden'; end if;
  if not exists (select 1 from public.cms_page_revisions where id = target_revision and page_id = target_page) then raise exception 'revision does not belong to page'; end if;
  select to_jsonb(p) into old_page from public.cms_pages p where id = target_page;
  update public.cms_pages set published_revision_id = target_revision, status = 'published', updated_at = now() where id = target_page;
  insert into public.admin_audit_logs(actor_id,action,domain,entity_type,entity_id,old_values,new_values)
  values(auth.uid(),'publish','cms','cms_page',target_page::text,coalesce(old_page,'{}'::jsonb),jsonb_build_object('published_revision_id',target_revision,'status','published'));
end;
$$;
revoke all on function public.publish_cms_revision(uuid,uuid) from public, anon;
grant execute on function public.publish_cms_revision(uuid,uuid) to authenticated;

create or replace function public.unpublish_cms_page(target_page uuid, event_reason text default null)
returns void language plpgsql security definer set search_path = '' as $$
declare old_page jsonb;
begin
  if not private.has_staff_permission('cms.publish') then raise exception 'forbidden'; end if;
  select to_jsonb(p) into old_page from public.cms_pages p where id = target_page;
  update public.cms_pages set status = 'unpublished', updated_at = now() where id = target_page;
  insert into public.admin_audit_logs(actor_id,action,domain,entity_type,entity_id,old_values,new_values,reason)
  values(auth.uid(),'unpublish','cms','cms_page',target_page::text,coalesce(old_page,'{}'::jsonb),jsonb_build_object('status','unpublished'),event_reason);
end;
$$;
revoke all on function public.unpublish_cms_page(uuid,text) from public, anon;
grant execute on function public.unpublish_cms_page(uuid,text) to authenticated;

create or replace function public.manage_staff_access(
  target_user uuid, target_role text, target_active boolean,
  target_status text default 'active', target_display_name text default '', event_reason text default null
) returns uuid language plpgsql security definer set search_path = '' as $$
declare selected_role_id uuid; assignment_id uuid; remaining_role text;
begin
  if not private.has_staff_permission('roles.manage') then raise exception 'forbidden'; end if;
  if target_user = auth.uid() then raise exception 'self role changes are forbidden'; end if;
  if target_status not in ('active','suspended','ended') then raise exception 'invalid staff status'; end if;
  select id into selected_role_id from public.staff_roles where key = target_role;
  if selected_role_id is null then raise exception 'invalid staff role'; end if;
  if target_active then
    insert into public.staff_profiles(user_id,role,display_name,status,created_by)
    values(target_user,target_role,left(coalesce(target_display_name,''),255),target_status,auth.uid())
    on conflict(user_id) do update set display_name = case when target_display_name <> '' then left(target_display_name,255) else public.staff_profiles.display_name end,
      status = target_status, role = target_role, updated_at = now();
    insert into public.staff_role_assignments(staff_user_id,role_id,assigned_by,reason)
    values(target_user,selected_role_id,auth.uid(),event_reason)
    on conflict(staff_user_id,role_id) where revoked_at is null do update set reason = excluded.reason returning id into assignment_id;
  else
    update public.staff_role_assignments set revoked_at = now(), revoked_by = auth.uid(), reason = event_reason
      where staff_user_id = target_user and role_id = selected_role_id and revoked_at is null returning id into assignment_id;
    select r.key into remaining_role from public.staff_role_assignments a join public.staff_roles r on r.id = a.role_id
      where a.staff_user_id = target_user and a.revoked_at is null
      order by case r.key when 'super_admin' then 1 when 'admin' then 2 when 'mentor' then 3 else 4 end limit 1;
    update public.staff_profiles set role = coalesce(remaining_role,role), status = case when remaining_role is null then 'ended' else target_status end, updated_at = now() where user_id = target_user;
  end if;
  insert into public.admin_audit_logs(actor_id,action,domain,entity_type,entity_id,target_user_id,new_values,reason)
  values(auth.uid(),case when target_active then 'staff_role_assigned' else 'staff_role_revoked' end,'staff','staff_role_assignment',assignment_id::text,target_user,
    jsonb_build_object('role',target_role,'active',target_active,'status',target_status),event_reason);
  return assignment_id;
end;
$$;
revoke all on function public.manage_staff_access(uuid,text,boolean,text,text,text) from public, anon;
grant execute on function public.manage_staff_access(uuid,text,boolean,text,text,text) to authenticated;

-- RLS for authorization and newly introduced modules.
alter table public.staff_roles enable row level security;
alter table public.staff_permissions enable row level security;
alter table public.staff_role_permissions enable row level security;
alter table public.staff_role_assignments enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.testimonials enable row level security;
alter table public.content_people enable row level security;
alter table public.site_notices enable row level security;
alter table public.legal_documents enable row level security;
alter table public.site_social_links enable row level security;
alter table public.university_meeting_slots enable row level security;
alter table public.premium_content_settings enable row level security;
alter table public.site_settings enable row level security;

create policy "staff read role definitions" on public.staff_roles for select to authenticated using (private.has_staff_permission('overview.read'));
create policy "staff read permission definitions" on public.staff_permissions for select to authenticated using (private.has_staff_permission('overview.read'));
create policy "staff read role permissions" on public.staff_role_permissions for select to authenticated using (private.has_staff_permission('staff.read'));
create policy "staff read own or authorized assignments" on public.staff_role_assignments for select to authenticated using (staff_user_id = auth.uid() or private.has_staff_permission('staff.read'));
create policy "authorized staff read staff directory" on public.staff_profiles for select to authenticated using (private.has_staff_permission('staff.read'));
create policy "authorized staff read student directory" on public.profiles for select to authenticated using (private.has_staff_permission('students.read'));
create policy "authorized staff read entitlements" on public.premium_entitlements for select to authenticated using (private.has_staff_permission('students.read'));
create policy "audit readers inspect admin audit" on public.admin_audit_logs for select to authenticated using (private.has_staff_permission('audit.read'));

-- Replace the proof-editor policies. cms_editors no longer grants production CMS authority.
drop policy if exists "editors manage cms pages" on public.cms_pages;
drop policy if exists "editors create cms revisions" on public.cms_page_revisions;
drop policy if exists "editors read cms revisions" on public.cms_page_revisions;
drop policy if exists "editors manage media metadata" on public.media_assets;
create policy "staff read cms pages" on public.cms_pages for select to authenticated using (private.has_staff_permission('cms.read'));
create policy "staff manage cms pages" on public.cms_pages for all to authenticated using (private.has_staff_permission('cms.manage')) with check (private.has_staff_permission('cms.manage'));
create policy "staff read cms revisions" on public.cms_page_revisions for select to authenticated using (private.has_staff_permission('cms.read'));
create policy "staff create cms revisions" on public.cms_page_revisions for insert to authenticated with check (private.has_staff_permission('cms.manage') and created_by = auth.uid());
create policy "staff read media metadata" on public.media_assets for select to authenticated using (private.has_staff_permission('media.read'));
create policy "staff manage media metadata" on public.media_assets for all to authenticated using (private.has_staff_permission('media.manage')) with check (private.has_staff_permission('media.manage') and created_by = auth.uid());

-- Catalog staff policies supplement the existing published-public policies.
do $$ declare table_name text; begin
  foreach table_name in array array['countries','universities','programs','course_categories','courses','event_categories','events','event_facilitators','catalog_tags','program_tags','course_tags','event_tags','catalog_filter_facets','catalog_filter_options','program_filter_options','course_filter_options','event_filter_options','university_filter_options'] loop
    execute format('create policy "staff read %1$s" on public.%1$I for select to authenticated using (private.has_staff_permission(''catalog.read''))', table_name);
    execute format('create policy "staff manage %1$s" on public.%1$I for all to authenticated using (private.has_staff_permission(''catalog.manage'')) with check (private.has_staff_permission(''catalog.manage''))', table_name);
  end loop;
end $$;

-- Existing and new structured content modules.
do $$ declare table_name text; begin
  foreach table_name in array array['faqs','weekly_wall_items','key_dates','urgent_deadlines','study_abroad_facts','pgs_stats','testimonials','content_people','site_notices','legal_documents','site_social_links','university_meeting_slots','premium_content_settings'] loop
    execute format('create policy "staff read %1$s" on public.%1$I for select to authenticated using (private.has_staff_permission(''content.read''))', table_name);
    execute format('create policy "staff manage %1$s" on public.%1$I for all to authenticated using (private.has_staff_permission(''content.manage'')) with check (private.has_staff_permission(''content.manage''))', table_name);
  end loop;
end $$;
create policy "public reads testimonials" on public.testimonials for select to anon, authenticated using (published);
create policy "public reads content people" on public.content_people for select to anon, authenticated using (published);
create policy "public reads active notices" on public.site_notices for select to anon, authenticated using (active and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now()));
create policy "public reads legal documents" on public.legal_documents for select to anon, authenticated using (status = 'published');
create policy "public reads social links" on public.site_social_links for select to anon, authenticated using (published);
create policy "public reads meeting slots" on public.university_meeting_slots for select to anon, authenticated using (published);
create policy "public reads premium content settings" on public.premium_content_settings for select to anon, authenticated using (published);

do $$ declare table_name text; begin
  foreach table_name in array array['enquiries','lead_submissions','study_journey_enquiries','deadline_subscriptions'] loop
    execute format('create policy "staff read %1$s" on public.%1$I for select to authenticated using (private.has_staff_permission(''leads.read''))', table_name);
    execute format('create policy "staff triage %1$s" on public.%1$I for update to authenticated using (private.has_staff_permission(''leads.manage'')) with check (private.has_staff_permission(''leads.manage''))', table_name);
  end loop;
end $$;
create policy "staff read site settings" on public.site_settings for select to authenticated using (private.has_staff_permission('settings.read'));
create policy "staff manage site settings" on public.site_settings for all to authenticated using (private.has_staff_permission('settings.manage')) with check (private.has_staff_permission('settings.manage') and updated_by = auth.uid());

-- Append-only audit triggers for privileged operational rows.
do $$ declare table_name text; begin
  foreach table_name in array array['countries','universities','programs','course_categories','courses','event_categories','events','event_facilitators','catalog_tags','catalog_filter_facets','catalog_filter_options','cms_pages','cms_page_revisions','media_assets','faqs','weekly_wall_items','key_dates','urgent_deadlines','study_abroad_facts','pgs_stats','testimonials','content_people','site_notices','legal_documents','site_social_links','university_meeting_slots','premium_content_settings','site_settings','enquiries','lead_submissions','study_journey_enquiries','deadline_subscriptions'] loop
    execute format('create trigger audit_%1$I_admin after insert or update or delete on public.%1$I for each row execute function private.audit_admin_change()', table_name);
  end loop;
end $$;

-- Public marketing media and private preview media remain separate from student documents.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
  ('marketing-public','marketing-public',true,10485760,array['image/jpeg','image/png','image/webp','image/gif','image/svg+xml','video/mp4','application/pdf']),
  ('cms-previews','cms-previews',false,10485760,array['image/jpeg','image/png','image/webp','image/gif','video/mp4','application/pdf'])
on conflict(id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
create policy "staff read cms preview objects" on storage.objects for select to authenticated using (bucket_id = 'cms-previews' and private.has_staff_permission('media.read'));

-- Grants remain broad enough for PostgREST; RLS is the authority.
revoke all on public.staff_roles,public.staff_permissions,public.staff_role_permissions,public.staff_role_assignments,public.admin_audit_logs,
  public.testimonials,public.content_people,public.site_notices,public.legal_documents,public.site_social_links,
  public.university_meeting_slots,public.premium_content_settings,public.site_settings from anon,authenticated;
grant select on public.staff_roles,public.staff_permissions,public.staff_role_permissions,public.staff_role_assignments,public.admin_audit_logs to authenticated;
grant select on public.testimonials,public.content_people,public.site_notices,public.legal_documents,public.site_social_links,public.university_meeting_slots,public.premium_content_settings to anon,authenticated;
grant insert,update,delete on public.testimonials,public.content_people,public.site_notices,public.legal_documents,public.site_social_links,public.university_meeting_slots,public.premium_content_settings to authenticated;
grant select,insert,update,delete on public.site_settings to authenticated;
grant insert,update,delete on public.countries,public.universities,public.programs,public.course_categories,public.courses,public.event_categories,public.events,public.event_facilitators,public.catalog_tags,public.program_tags,public.course_tags,public.event_tags,public.catalog_filter_facets,public.catalog_filter_options,public.program_filter_options,public.course_filter_options,public.event_filter_options,public.university_filter_options to authenticated;
grant insert,update,delete on public.faqs,public.weekly_wall_items,public.key_dates,public.urgent_deadlines,public.study_abroad_facts,public.pgs_stats to authenticated;
grant update on public.enquiries,public.lead_submissions,public.study_journey_enquiries,public.deadline_subscriptions to authenticated;
grant usage,select on all sequences in schema public to authenticated;

insert into public.premium_content_settings(key,title) values ('video','Purple Premium video'),('meetup','Purple Premium meetup') on conflict(key) do nothing;
insert into public.legal_documents(document_type,title) values ('privacy','Privacy Policy'),('terms','Terms and Conditions'),('refund','Refund Policy') on conflict(document_type) do nothing;
