create table public.cms_editors (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.page_content (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug in ('home', 'countriesusa')),
  content jsonb not null check (jsonb_typeof(content) = 'object'),
  published boolean not null default false,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create or replace function public.touch_page_content_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger touch_page_content_updated_at
before update on public.page_content
for each row execute function public.touch_page_content_updated_at();

alter table public.cms_editors enable row level security;
alter table public.page_content enable row level security;

create policy "editors can inspect their own membership"
on public.cms_editors for select
to authenticated
using (user_id = (select auth.uid()));

create policy "public can read published proof content"
on public.page_content for select
to anon, authenticated
using (published = true);

create policy "editors can read draft proof content"
on public.page_content for select
to authenticated
using (exists (select 1 from public.cms_editors where user_id = (select auth.uid())));

create policy "editors can insert proof content"
on public.page_content for insert
to authenticated
with check (
  updated_by = (select auth.uid())
  and exists (select 1 from public.cms_editors where user_id = (select auth.uid()))
);

create policy "editors can update proof content"
on public.page_content for update
to authenticated
using (exists (select 1 from public.cms_editors where user_id = (select auth.uid())))
with check (
  updated_by = (select auth.uid())
  and exists (select 1 from public.cms_editors where user_id = (select auth.uid()))
);

revoke all on public.cms_editors from anon, authenticated;
grant select on public.cms_editors to authenticated;
revoke all on public.page_content from anon, authenticated;
grant select on public.page_content to anon, authenticated;
grant insert, update on public.page_content to authenticated;
grant usage, select on sequence public.page_content_id_seq to authenticated;

insert into public.page_content (slug, content, published)
values
  ('home', '{"heroSupport":"Join #PGS — whether it’s Medical Pathway, STEM, Master’s, or other programs, we’ve got your admission roadmap.","introTitle":"One of the best parts of #PGS? The Student Dashboard.","introBody":"Get real-time updates, mentor feedback, and full progress tracking—every step from Day 1 to your admit. Everything stays mapped, organized, and right here in one place."}'::jsonb, true),
  ('countriesusa', '{"titleLineOne":"Comprehensive Guide to","titleLineTwo":"Studying in the USA","subtitle":"Best Universities, Programs, Costs & Admission Criteria for International Students","kicker":"For Medical, STEM, and More—We’ve Got You Covered","contactCta":"Got Questions? Talk to Us"}'::jsonb, true);
