import Link from "next/link";
import { AdminPageHeader } from "@/components/admin-page-header";
import { can,requireStaffPermission } from "@/lib/staff-auth";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type Student={id:string;full_name:string;email:string;profile_status:string;study_level:string|null;premium:string;mentor:string};
export default async function StudentsPage({searchParams}:{searchParams:Promise<{q?:string;premium?:string}>}){const context=await requireStaffPermission("overview.read");const filters=await searchParams;const supabase=await createSupabaseServerClient();let students:Student[]=[];
  if(can(context,"students.read")){let query=supabase.from("profiles").select("id,full_name,email,profile_status,study_level").order("created_at",{ascending:false}).limit(150);if(filters.q)query=query.or(`full_name.ilike.%${filters.q.slice(0,80)}%,email.ilike.%${filters.q.slice(0,80)}%`);const {data:profiles}=await query;const ids=(profiles??[]).map((profile)=>profile.id);const [{data:entitlements},{data:assignments}]=ids.length?await Promise.all([supabase.from("premium_entitlements").select("student_id,status").in("student_id",ids),supabase.from("mentor_assignments").select("student_id,staff_profiles!mentor_assignments_mentor_id_fkey(display_name)").in("student_id",ids).eq("status","active")]):[{data:[]},{data:[]}];const premium=new Map((entitlements??[]).map((row)=>[row.student_id,row.status]));const mentors=new Map((assignments??[]).map((row)=>{const relation=row.staff_profiles as unknown as {display_name:string}|Array<{display_name:string}>|null;return [row.student_id,Array.isArray(relation)?relation[0]?.display_name??"Assigned":relation?.display_name??"Assigned"]}));students=(profiles??[]).map((profile)=>({...profile,premium:premium.get(profile.id)??"none",mentor:mentors.get(profile.id)??"Unassigned"}));
  }else{const {data:assignments}=await supabase.from("mentor_assignments").select("student_id,profiles!mentor_assignments_student_id_fkey(id,full_name,email,profile_status,study_level)").eq("mentor_id",context.user.id).eq("status","active");students=(assignments??[]).flatMap((assignment)=>{const relation=assignment.profiles as unknown as Student|Student[]|null;const profile=Array.isArray(relation)?relation[0]:relation;return profile?[{...profile,premium:"active",mentor:context.displayName}]:[]});}
  if(filters.premium)students=students.filter((student)=>student.premium===filters.premium);
  return <main className="ops-page"><AdminPageHeader eyebrow="Students" title={can(context,"students.read")?"Student operations":"Assigned student workspaces"} description="Staff views use the same identity, entitlement, documents, comments, and board rows as each student." actions={can(context,"premium.manage")?<Link className="ops-primary" href="/admin/access">Premium & mentor controls</Link>:undefined}/><section className="ops-crud"><div className="ops-toolbar"><form method="get" role="search"><input name="q" type="search" defaultValue={filters.q} placeholder="Search name or email…"/><select name="premium" defaultValue={filters.premium??""}><option value="">All Premium states</option><option value="active">Active Premium</option><option value="revoked">Revoked</option><option value="none">No entitlement</option></select><button>Filter</button></form></div><div className="ops-table-wrap"><table><thead><tr><th>Student</th><th>Profile</th><th>Study level</th><th>Premium</th><th>Mentor</th><th>Workspace</th></tr></thead><tbody>{students.map((student)=><tr key={student.id}><td><strong>{student.full_name||"Student"}</strong><br/><span>{student.email}</span></td><td><span className="ops-badge">{student.profile_status}</span></td><td>{student.study_level||"—"}</td><td><span className={`ops-badge is-${student.premium}`}>{student.premium}</span></td><td>{student.mentor}</td><td>{(student.premium==="active"&&(can(context,"student_workspace.read_all")||can(context,"student_workspace.read")))?<Link href={`/admin/students/${student.id}`}>Open workspace →</Link>:<span>Read-only profile</span>}</td></tr>)}</tbody></table></div></section></main>}

